/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "gpio.h"
#include "stub.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void delay(uint32_t Time_u32)
{
	for(uint32_t i = 0; i<Time_u32; i++);
}

Gpio_Config Config1 =
{
	.Gpio_PinNum_e = GPIO_PINNUM_1,
	.Gpio_PinMode_e = GPIO_MODE_OUT,
	.Gpio_PinSpeed_e = GPIO_OUTSPEED_LOW,
	.Gpio_PinPuPd_e = GPIO_PULLUPDOWN_NOPULL,
	.Gpio_PinOutType_e = GPIO_OUTTYPE_PUSPUL,
	.Gpio_PinAltFun_e = GPIO_ALTFUN_0
};

Gpio_Handle ConfigLed =
{
	.p_Gpio_Base_st = GPIOB,
	.p_Gpio_Config_st = &Config1
};

Gpio_Config Config2 =
{
	.Gpio_PinNum_e = GPIO_PINNUM_2,
	.Gpio_PinMode_e = GPIO_MODE_IR_FE,
	.Gpio_PinSpeed_e = GPIO_OUTSPEED_LOW,
	.Gpio_PinPuPd_e = GPIO_PULLUPDOWN_NOPULL,
	.Gpio_PinOutType_e = GPIO_OUTTYPE_OPENDR,
	.Gpio_PinAltFun_e = GPIO_ALTFUN_0
};

Gpio_Handle ConfigBt =
{
	.p_Gpio_Base_st = GPIOB,
	.p_Gpio_Config_st = &Config2
};

int main(void)
{
	RCC_GPIOB_CLK_EN();
	Gpio_Init(&ConfigLed);
	Gpio_Init(&ConfigBt);
	Gpio_IrqConfig(IRQ_NUM_EXTI2, 2U, ENABLE);
	while(1);
//	{
//		if(0 == Gpio_ReadPin(GPIOB, GPIO_PINNUM_2))
//		{
//			//Gpio_ToggleOutPin(GPIOA, GPIO_PINNUM_5);
//			//delay(1000000);
//			Gpio_WritePin(GPIOB, GPIO_PINNUM_1, GPIO_RESET);
//		}
//		else
//		{
//			Gpio_WritePin(GPIOB, GPIO_PINNUM_1, GPIO_SET);
//		}
//	}
//    /* Loop forever */
//	for(;;);
}

void EXTI2_IRQHandler(void)
{
	delay(500000);
	Gpio_IrqHandler(GPIO_PINNUM_2);
	Gpio_ToggleOutPin(GPIOB, GPIO_PINNUM_1);
}
